packages:
  # Core packages - Foundation of the platform
  - "core/*"
  
  # Shared packages - UI, utilities, etc.
  - "packages/*"
  
  # Services - Backend microservices
  - "services/*"
  
  # Applications - Frontend apps
  - "apps/*"
  
  # Documentation as packages (if needed)
  # - "docs/*"

# Catalog configuration for better dependency management
catalog:
  # Core dependencies
  typescript: ^5.7.2
  "@types/node": ^20.0.0
  
  # React ecosystem
  react: ^18.3.0
  "react-dom": ^18.3.0
  "@types/react": ^18.3.0
  "@types/react-dom": ^18.3.0
  
  # Database
  prisma: ^5.20.0
  "@prisma/client": ^5.20.0
  
  # Express ecosystem
  express: ^4.18.0
  "@types/express": ^4.17.0
  
  # Utility libraries
  zod: ^3.23.0
  date-fns: ^3.0.0